### ISSUE TITLE
Input is handled too concretely by abstractFighter.py and other files

### ISSUE THREAD

**Issue by meffij** [digiholic/universalSmashSystem#15]
This isn't an immediate functional issue, but it will result in difficulty when someone wants to change how inputs work. Currently, fighters determine their next action by reading keys directly, which makes adding an input buffer or changing how smash attacks are input, etc. much harder, because you have to change the input handling code for each fighter.

I propose the following paradigm instead -- players use the main menu to map their controls to a standard set of controls -- A GameCube controller, for instance, has 2 sticks with 2 analog axes each, 2 triggers with 2 analog axes each, and 12 digital inputs (4 for D-pad, A, B, X, Y, Z, Ldigital, Rdigital, Start). So a controller object in TUSSLE is a collection of sticks, trigger axes, and buttons.

We start by standardizing what format all these values are represented in. Analog axes are usually floats between 0.0 and 1.0 at the system level, so that should work fine. Buttons are just boolean values. Then, we just need some container object for all these axes and buttons that is exposed to the fighter code. So, instead of having specific input handling code in any particular fighter.py, fighters just see a standard representation of inputs, a virtual GameCube controller that it knows how to deal with.

I'd just start making changes and make a pull request eventually, but I wanted some feedback first before I start refactoring a lot of code. I don't want to railroad your project, I just want to be helpful and a good community member. I'm interested in everyone's thoughts on how the input subsystem should be handled.

**Comment by meffij** [comment]
Actually I think I might be misreading the input code. If you could explain how inputs are handled in a few sentences, I'd really appreciate it. I'll try to figure it out on my own though.

**Comment by digiholic** [comment]
Input is currently handled by a kebindings dict that maps a key input to an action, a word like 'jump' or 'attack', and vice-versa. When the battle object (which is running the core event loop) gets a key input, it passes it to all of the fighters, basically saying "here, I got this key. Do with it what you will." If that key maps to an action, the fighter does that action. So, you could have two buttons that map to 'jump' (let's call them X and Y), and if the battle gets an X input, it passes it to the fighter, which checks it's keybindings and sees that X matches with 'jump', so it executes its 'jump' command.

It's highly possible you might be seeing the half-implemented gamepad code. It's currently hard-coded in that, because right now we're just trying to get the gamepad working, and we'll clean it up later.

Hope that answers your question.

**Comment by meffij** [comment]
I think it does. Thanks!

Maybe we should establish a better line of communication than the issue tracker on your GitHub. Any suggestions? People seem to like Discord, but I know very little about it.

**Comment by digiholic** [comment]
Concrete controls have been done away with in the AI update, fighters now get raw strings (such as 'left' or 'right') instead of a button. This allows "virtual players" to hit buttons without keybindings.
